[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "netlify-plugin-cypress"
  [plugins.inputs.postBuild]
    enable = false

  [plugins.inputs]
    enable = false

[[plugins]]
package = "netlify-build-plugin-pushover"

  [plugins.inputs]
    successMessage = "" #Optional
    errorMessage = "" #Optional

    [[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"

  # explicit commands for building the site
# and the folder to publish
[build]
command = "npm run build"
publish = "build"

[build.environment]
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"

[[plugins]]
# runs Cypress tests against the deployed URL
package = "netlify-plugin-cypress"